language: python
python:
  - "2.7"
  - "3.4"

install:
  - sudo apt-get -qq install libatlas-base-dev gfortran
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements-2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements-3.txt; fi
  - pip install pep8

# Ensure `requirements.txt` contains all of the dependencies
# for the scripts and that scripts that only operate on
# command-line arguments can be executed.
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then ./.travis-script-2.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./.travis-script-3.sh; fi